import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head >
        <title>Yash Portfolio</title>
        <meta name="description" content="Generated by Yash" />
        <link rel="icon" href="/yash.jpg" />

      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
